# Numpy

- Numpy is the fundamental package for scientific computing in python.
- It is the py library that provides mullti-dimensional array objects, various derived obbjects (such as masked arrays and matrices), and an assortment of routines for fast operations on array including mathematical, statiscal, logical, shape manipulation, sorting, selecting, I/O,algebric,etc.

- At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

**Numpy arrays Vs Python Srequences**

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Creating Numpy Arrays

In [5]:
# np.array
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
# 2D and 3D
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
c=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [9]:
# dtype
d=np.array([1,2,3,4],dtype=float)
print(d)

[1. 2. 3. 4.]


In [10]:
d=np.array([1,2,3,4],dtype=bool)
print(d)

[ True  True  True  True]


In [11]:
#np.arange
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
# with reshape
a=np.arange(1,11).reshape(5,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [16]:
# np.ones and np.zeros
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
# np.random
a=np.random.random((3,4))
print(a)

[[0.94360366 0.61841108 0.04445066 0.87007023]
 [0.69624202 0.61552422 0.03601028 0.31989254]
 [0.81000088 0.47578369 0.37187375 0.88619828]]


In [28]:
# np.linspace
a=np.linspace(-10,10,10)
print(a)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [29]:
# np.identity
np.identity(2)

array([[1., 0.],
       [0., 1.]])

# Array Attributes

In [30]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [31]:
# ndim
a1.ndim

1

In [32]:
a2.ndim

2

In [33]:
a3.ndim

3

In [34]:
# shape
a1.shape

(10,)

In [35]:
a2.shape

(3, 4)

In [36]:
a3.shape

(2, 2, 2)

In [37]:
# size
a1.size

10

In [38]:
a2.size

12

In [39]:
a3.size

8

In [40]:
#itemsize
a1.itemsize

8

In [41]:
a2.itemsize

8

In [42]:
a3.itemsize

8

# Changing datatype

In [49]:
# astype
a3.astype(np.int32)

array([[[0, 0, 1, 0],
        [2, 0, 3, 0]],

       [[4, 0, 5, 0],
        [6, 0, 7, 0]]], dtype=int32)

In [50]:
a3.dtype

dtype('int32')

# Array Operations

In [51]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [52]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
# scalar operation
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [55]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [57]:
# relational
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
# Vector operation
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [59]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [60]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [61]:
a1-a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

# Array Functions

In [62]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[69., 68.,  5.],
       [29., 32., 86.],
       [51., 97., 56.]])

In [68]:
# max/min/sum/prod
np.max(a1)

np.float64(97.0)

In [69]:
np.min(a1)

np.float64(5.0)

In [70]:
np.sum(a1)

np.float64(493.0)

In [71]:
np.prod(a1)

np.float64(518685816821760.0)

In [74]:
np.min(a1,axis=1) #1:row and 0:col

array([ 5., 29., 51.])

In [75]:
# mean/median/std/var
np.mean(a1)

np.float64(54.77777777777778)

In [76]:
np.median(a1)

np.float64(56.0)

In [77]:
np.std(a1)

np.float64(27.51071620610484)

In [78]:
np.var(a1)

np.float64(756.8395061728395)

In [79]:
# Trigonometric
np.sin(a1)

array([[-0.11478481, -0.89792768, -0.95892427],
       [-0.66363388,  0.55142668, -0.92345845],
       [ 0.67022918,  0.37960774, -0.521551  ]])

In [80]:
# dot product
a1=np.arange(1,11).reshape(2,5)
a2=np.arange(11,21).reshape(5,2)

In [81]:
np.dot(a1,a2)

array([[245, 260],
       [620, 660]])

In [82]:
# log and exponents
np.log(a1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [83]:
np.exp(a1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [87]:
# round/ floor/ceil
a1=np.random.random((2,5))*100
a1

array([[20.49757631, 14.77374954, 19.96922273, 86.91936002, 39.92861303],
       [79.01314795, 61.49811984, 60.97213955, 74.81967007,  8.64315457]])

In [88]:
np.round(a1)

array([[20., 15., 20., 87., 40.],
       [79., 61., 61., 75.,  9.]])

In [89]:
np.floor(a1)

array([[20., 14., 19., 86., 39.],
       [79., 61., 60., 74.,  8.]])

In [90]:
np.ceil(a1)

array([[21., 15., 20., 87., 40.],
       [80., 62., 61., 75.,  9.]])

# Indexing and Slicing

In [91]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [92]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
a1[-1]

np.int64(9)

In [96]:
a1[0]

np.int64(0)

In [97]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
a2[1,2]

np.int64(6)

In [100]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [101]:
a3[1,0,1]

np.int64(5)

In [102]:
a3[0,1,0]

np.int64(2)

In [103]:
a3[0,0,0]

np.int64(0)

In [104]:
a3[1,1,0]

np.int64(6)

In [105]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
a1[2:5]

array([2, 3, 4])

In [107]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a2[0,:]

array([0, 1, 2, 3])

In [110]:
a2[:,2]

array([ 2,  6, 10])

In [111]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [114]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [115]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [116]:
a2[1,::3]

array([4, 7])

In [117]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [121]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [122]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [123]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [124]:
a3[0,1,:]

array([3, 4, 5])

In [125]:
a3[1,:,1]

array([10, 13, 16])

In [127]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [130]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [135]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [136]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [137]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [134]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# Reshaping

In [138]:
# reshape


In [139]:
# transpose
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [141]:
# ravela
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [143]:
# Horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [145]:
a=np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [147]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [148]:
# Horizontal
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [151]:
a4=np.arange(4).reshape(2,2)

In [152]:
np.vsplit(a4,2)

[array([[0, 1]]), array([[2, 3]])]

In [ ]:
d