In [2]:
# np.sort
import numpy as np
a=np.random.randint(1,100,15)
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [3]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[68, 77, 52, 87],
       [14, 88, 54, 82],
       [ 6, 58, 60, 25],
       [46, 54, 10, 72],
       [34, 63, 17, 88],
       [25, 54, 81, 27]], dtype=int32)

In [4]:
np.sort(a)

array([11, 11, 25, 28, 29, 42, 57, 60, 63, 69, 76, 78, 79, 81, 87],
      dtype=int32)

In [5]:
np.sort(b,axis=0) # column-wise sorting

array([[ 6, 54, 10, 25],
       [14, 54, 17, 27],
       [25, 58, 52, 72],
       [34, 63, 54, 82],
       [46, 77, 60, 87],
       [68, 88, 81, 88]], dtype=int32)

In [6]:
np.sort(a)[::-1]

array([87, 81, 79, 78, 76, 69, 63, 60, 57, 42, 29, 28, 25, 11, 11],
      dtype=int32)

In [7]:
# np.append
# The numpy.append() appends values along the mentioned axis at the end of the array
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [8]:
np.append(a,100)

array([ 81,  76,  63,  28,  60,  42,  25,  69,  78,  29,  79,  57,  11,
        11,  87, 100])

In [9]:
b

array([[68, 77, 52, 87],
       [14, 88, 54, 82],
       [ 6, 58, 60, 25],
       [46, 54, 10, 72],
       [34, 63, 17, 88],
       [25, 54, 81, 27]], dtype=int32)

In [10]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[68., 77., 52., 87.,  1.],
       [14., 88., 54., 82.,  1.],
       [ 6., 58., 60., 25.,  1.],
       [46., 54., 10., 72.,  1.],
       [34., 63., 17., 88.,  1.],
       [25., 54., 81., 27.,  1.]])

In [11]:
# np.concatenate
# The numpy.concatenate() function is used to join two or more arrays of the same shape along
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

c

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [15]:
# np.unique
# The numpy.unique() function is used to find the unique elements of an array.
e=np.array([1,1,2,2,3,3,4,4,5,5])
np.unique(e)

array([1, 2, 3, 4, 5])

In [16]:
# np.expand_dims
# The numpy.expand_dims() function is used to expand the shape of an array by inserting a
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [17]:
np.expand_dims(a,axis=0)

array([[81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87]],
      dtype=int32)

In [18]:
np.expand_dims(a,axis=1)

array([[81],
       [76],
       [63],
       [28],
       [60],
       [42],
       [25],
       [69],
       [78],
       [29],
       [79],
       [57],
       [11],
       [11],
       [87]], dtype=int32)

In [19]:
# np.where
# The numpy.where() function is used to select elements from an array based on a condition.
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [20]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  4,  7,  8, 10, 11, 14]),)

In [21]:
np.where(a>50,0,a)

array([ 0,  0,  0, 28,  0, 42, 25,  0,  0, 29,  0,  0, 11, 11,  0],
      dtype=int32)

In [22]:
np.where(a%2==0,0,a)

array([81,  0, 63,  0,  0,  0, 25, 69,  0, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [23]:
# np.argmax
# The numpy.argmax() function is used to find the index of the maximum value in an array
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [24]:
np.argmax(a)

np.int64(14)

In [25]:
b

array([[68, 77, 52, 87],
       [14, 88, 54, 82],
       [ 6, 58, 60, 25],
       [46, 54, 10, 72],
       [34, 63, 17, 88],
       [25, 54, 81, 27]], dtype=int32)

In [26]:
np.argmax(b,axis=1)

array([3, 1, 2, 3, 3, 2])

In [27]:
# np.argmin
# The numpy.argmin() function is used to find the index of the minimum value in an array    
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [28]:
np.argmin(a)

np.int64(12)

In [29]:
# np.cumsum
# The numpy.cumsum() function is used to calculate the cumulative sum of the elements along a
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [30]:
np.cumsum(a)

array([ 81, 157, 220, 248, 308, 350, 375, 444, 522, 551, 630, 687, 698,
       709, 796])

In [31]:
b

array([[68, 77, 52, 87],
       [14, 88, 54, 82],
       [ 6, 58, 60, 25],
       [46, 54, 10, 72],
       [34, 63, 17, 88],
       [25, 54, 81, 27]], dtype=int32)

In [32]:
np.cumsum(b)

array([  68,  145,  197,  284,  298,  386,  440,  522,  528,  586,  646,
        671,  717,  771,  781,  853,  887,  950,  967, 1055, 1080, 1134,
       1215, 1242])

In [33]:
np.cumsum(b,axis=1)

array([[ 68, 145, 197, 284],
       [ 14, 102, 156, 238],
       [  6,  64, 124, 149],
       [ 46, 100, 110, 182],
       [ 34,  97, 114, 202],
       [ 25,  79, 160, 187]])

In [34]:
# np.cumprod
# The numpy.cumprod() function is used to calculate the cumulative product of the elements along
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [35]:
np.cumprod(a)

array([                  81,                 6156,               387828,
                   10859184,            651551040,          27365143680,
               684128592000,       47204872848000,     3681980082144000,
         106777422382176000,  8435416368191904000,  1203387070490185984,
       -5209486298317505792, -1964117060363908864, -4857487588274106624])

In [36]:
# np.percentile
# The numpy.percentile() function is used to compute the nth percentile of the data along the
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [38]:
np.percentile(a,100)

np.float64(87.0)

In [40]:
# np.histogram
# The numpy.histogram() function is used to compute the histogram of a set of data.
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 3, 0, 1, 1, 3, 3, 2, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [42]:
# np.corrcoef
# The numpy.corrcoef() function is used to compute the correlation coefficient of two or more
salary=np.array([1000,2000,3000,4000,5000])
exp=np.array([1,2,1,4,5])
np.corrcoef(salary,exp)

array([[1.        , 0.87038828],
       [0.87038828, 1.        ]])

In [44]:
# np.isin
# The numpy.isin() function is used to check if the elements of an array are present in another
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [47]:
items=[10,11,20,30,40,50]
a[np.isin(a,items)]

array([11, 11], dtype=int32)

In [48]:
# np.flip
# The numpy.flip() function is used to reverse the order of elements in an array along the
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [49]:
np.flip(a)

array([87, 11, 11, 57, 79, 29, 78, 69, 25, 42, 60, 28, 63, 76, 81],
      dtype=int32)

In [50]:
b

array([[68, 77, 52, 87],
       [14, 88, 54, 82],
       [ 6, 58, 60, 25],
       [46, 54, 10, 72],
       [34, 63, 17, 88],
       [25, 54, 81, 27]], dtype=int32)

In [51]:
np.flip(b,axis=0)

array([[25, 54, 81, 27],
       [34, 63, 17, 88],
       [46, 54, 10, 72],
       [ 6, 58, 60, 25],
       [14, 88, 54, 82],
       [68, 77, 52, 87]], dtype=int32)

In [53]:
np.flip(b,axis=1)

array([[87, 52, 77, 68],
       [82, 54, 88, 14],
       [25, 60, 58,  6],
       [72, 10, 54, 46],
       [88, 17, 63, 34],
       [27, 81, 54, 25]], dtype=int32)

In [55]:
# np.put
# The numpy.put() function is used to set the values of an array at specific indices.
a

array([81, 76, 63, 28, 60, 42, 25, 69, 78, 29, 79, 57, 11, 11, 87],
      dtype=int32)

In [60]:
np.put(a,[0,1],[110,530])

In [61]:
a

array([110, 530,  63,  28,  60,  42,  25,  69,  78,  29,  79,  57, 101,
       101,  87], dtype=int32)

In [62]:
# np.delete
# The numpy.delete() function is used to delete elements from an array along the specified axis.
a

array([110, 530,  63,  28,  60,  42,  25,  69,  78,  29,  79,  57, 101,
       101,  87], dtype=int32)

In [63]:
np.delete(a,[0])

array([530,  63,  28,  60,  42,  25,  69,  78,  29,  79,  57, 101, 101,
        87], dtype=int32)

# Set functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [65]:
m=np.array([1,2,3,4,5])
n=np.array([4,5,6,7,8])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
np.intersect1d(m,n)

array([4, 5])

In [67]:
np.setdiff1d(m,n)

array([1, 2, 3])

In [68]:
np.setxor1d(m,n)

array([1, 2, 3, 6, 7, 8])

In [71]:
np.in1d(m,2)

C:\Users\Anjali\AppData\Local\Temp\ipykernel_5628\595628413.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,2)


array([False,  True, False, False, False])

In [72]:
# np.clip
# The numpy.clip() function is used to limit the values in an array to a specified range.   
a

array([110, 530,  63,  28,  60,  42,  25,  69,  78,  29,  79,  57, 101,
       101,  87], dtype=int32)

In [73]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 63, 28, 60, 42, 25, 69, 75, 29, 75, 57, 75, 75, 75],
      dtype=int32)

In [74]:
# np.swapaxes
# The numpy.swapaxes() function is used to swap the axes of an array.
b

array([[68, 77, 52, 87],
       [14, 88, 54, 82],
       [ 6, 58, 60, 25],
       [46, 54, 10, 72],
       [34, 63, 17, 88],
       [25, 54, 81, 27]], dtype=int32)

In [75]:
np.swapaxes(b,0,1)

array([[68, 14,  6, 46, 34, 25],
       [77, 88, 58, 54, 63, 54],
       [52, 54, 60, 10, 17, 81],
       [87, 82, 25, 72, 88, 27]], dtype=int32)

In [77]:
# np.uniform
# The numpy.uniform() function is used to generate random numbers from a uniform distribution.
u=np.random.uniform(1,10,10)
u


array([6.31282052, 7.88421304, 4.88690795, 8.17032128, 5.01269954,
       3.16198974, 6.29448776, 8.3134886 , 3.17605518, 9.76697932])

In [80]:
# np.count_nonzero
# The numpy.count_nonzero() function is used to count the number of non-zero elements in
a_=np.array([0,0,1,2,3,4,5,6,7,8,9])
a_

array([0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.count_nonzero(a_)

np.int64(9)

In [82]:
# np.tile
# The numpy.tile() function is used to construct an array by repeating a given array the specified number of times.
a_

array([0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.tile(a_,2)

array([0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
# np.repeat
# The numpy.repeat() function is used to repeat elements of an array.
a_

array([0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
np.repeat(a_,3)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6,
       6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9])

In [87]:
# np.allclose
# The numpy.allclose() function is used to check if two arrays are element-wise equal within a tolerance.   
a=np.array([1,2,3])
b=np.array([1.0,2.0,3.0])
np.allclose(a,b)

True

In [93]:
# np.equal
# The numpy.equal() function is used to compare two arrays element-wise and return a boolean array indicating where the elements are equal.
a=[1,2,3]
b=[1,2,4]
np.equal(a,b)

array([ True,  True, False])